version: '3'
services:
  docker:
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - ./certs/client:/certs/client
    ports:
      - 2376:2376
  jenkins:
    build:
      context: .
    environment:
      - TZ=Asia/Seoul
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./certs/client:/certs/client:ro
    depends_on:
      - docker