version: '3'
services:
  jenkins:
    build:
      context: .
    environment:
      - TZ=Asia/Seoul
      # - DOCKER_HOST=tcp://docker:2376
      # - DOCKER_CERT_PATH=/certs/client
      # - DOCKER_TLS_VERIFY=1
    ports:
      - 8080:8080
    # privileged: true
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./certs/client:/certs/client:ro
      - /var/run/docker.sock:/var/run/docker.sock
  #   depends_on:
  #     - jenkins-docker    
  # jenkins-docker:
  #   image: docker:dind
  #   privileged: true
  #   environment:
  #     - DOCKER_TLS_CERTDIR=/certs
  #   ports:
  #     - 2376:2376
  #   volumes:
  #     - ./jenkins_home:/var/jenkins_home
  #     - ./certs/client:/certs/client
    
  